### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by spec56** [cynegeirus/public-openvpn-servers#1]
HI, I DOWNLOADED THE VPN OPEN FROM THE OFFICIAL WEBSITE, DOWNLOADED THESE PROFILES, THEY ARE LOADING AND CANNOT CONNECT TO ANY OF THE ENTIRE LIST OF PROFILES

**Comment by cynegeirus** [comment]
Hello, 

It can sometimes cause problems when connecting. This list will be updated soon. In the meantime, it is worth checking for available connections.
